import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = import.meta.dir;
const pngPath = join(dir, "..", "public", "favicon.png");
const outPath = join(dir, "..", "favicon-data.ts");

const buf = readFileSync(pngPath);
const base64 = buf.toString("base64");
writeFileSync(
  outPath,
  `// Generated by scripts/embed-favicon.ts – do not edit\n/** @type {string} */\nexport const FAVICON_BASE64 = ${JSON.stringify(base64)};\n`,
  "utf8"
);
console.log("Wrote favicon-data.ts");
